bones_intl.countries.all:
    pattern:  /country/list.{_format}
    defaults: { _controller: BonesCommonBundle:Location:countries, _format: json }
    requirements:
        _method: GET
    options:
            expose: true


bones_intl.state.all:
    pattern:  /state/list.{_format}
    defaults: { _controller: BonesCommonBundle:Location:states, _format: json }
    requirements:
        _method: GET
    options:
            expose: true

bones_intl.state.list.country:
    pattern:  /state/country/{countryCode}/list.{_format}
    defaults: { _controller: BonesCommonBundle:Location:statesByCountryCode, _format: json }
    requirements:
        _method: GET
    options:
            expose: true
