services:

    bones_intl.repository.location.country:
        class: Bones\IntlBundle\Model\Location\CountryRepository

    bones_intl.repository.location.state:
        class: Bones\IntlBundle\Model\Location\StateRepository
